

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: bancousers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend/crud
    container_name: spring_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bancousers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"